// fixtures
import { attributes } from '../../modules/attributes/fixtures';
import { brands } from '../../modules/brands/fixtures';
import { categories } from '../../modules/categories/fixtures';
import { ratings } from '../../modules/ratings/fixtures';
import { reviews } from '../../modules/reviews/fixtures';
import { shops } from '../../modules/shops/fixtures';

export const products = [
  {
    attributes,
    reviews,
    ratings,
    id: '1',
    name: 'Nice shirt',
    description: 'A beautiful nice shirt designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_005_shaco9.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '2',
    name: 'Nice cap',
    description: 'A beautiful nice cap designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_005_shaco9.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '3',
    name: 'Nice coat',
    description: 'A beautiful nice coat designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_005_shaco9.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '4',
    name: 'Nice top',
    description: 'A beautiful nice top designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_005_shaco9.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '5',
    name: 'Nice skirt',
    description: 'A beautiful nice skirt designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_005_shaco9.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '6',
    name: 'Nice shirt',
    description: 'A beautiful nice shirt designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_001_xaepru.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '7',
    name: 'Nice cap',
    description: 'A beautiful nice cap designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_001_xaepru.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '8',
    name: 'Nice coat',
    description: 'A beautiful nice coat designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_001_xaepru.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '9',
    name: 'Nice top',
    description: 'A beautiful nice top designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_001_xaepru.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '10',
    name: 'Nice skirt',
    description: 'A beautiful nice skirt designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209413/Man_001_xaepru.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
];

export const trendingProducts = [
  {
    attributes,
    reviews,
    ratings,
    id: '10',
    name: 'Nice timberland',
    description: 'A beautiful nice timberland designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209414/CU2-WATCHES_pgiyoc.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '10',
    name: 'Nice timberland',
    description: 'A beautiful nice timberland designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209414/TIMBERLAND001_elo3c3.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '10',
    name: 'Nice watch',
    description: 'A beautiful nice watch designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209414/CU2-WATCHES_pgiyoc.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
  {
    attributes,
    reviews,
    ratings,
    id: '10',
    name: 'Nice timberland',
    description: 'A beautiful nice timberland designed by the freshest designer.',
    discountPercent: '10',
    price: '2000',
    gender: 'male',
    brand: brands[0],
    quantity: 7,
    pictures: 'https://res.cloudinary.com/faksam-soft/image/upload/v1559209414/TIMBERLAND001_elo3c3.jpg',
    shop: shops[0],
    category: categories[1].name,
    createdAt: '05/12/19',
  },
];

export const menClothings = [
  {
    id: '1',
    name: 'Shirts',
    description: 'Shirts',
    createdAt:  '12/05/19',
  },
  {
    id: '2',
    name: 'T-Shirts',
    description: 'T-Shirts',
    createdAt:  '12/05/19',
  },
  {
    id: '3',
    name: 'Polo Shirts',
    description: 'Polo Shirts',
    createdAt:  '12/05/19',
  },
  {
    id: '4',
    name: 'Pants',
    description: 'Pants',
    createdAt:  '12/05/19',
  },
  {
    id: '5',
    name: 'Jeans',
    description: 'Jeans',
    createdAt:  '12/05/19',
  },
  {
    id: '6',
    name: 'Jumpers - Cardigans',
    description: 'Jumpers - Cardigans',
    createdAt:  '12/05/19',
  },
  {
    id: '7',
    name: 'Hoodies - Sweatshirts',
    description: 'Hoodies - Sweatshirts',
    createdAt:  '12/05/19',
  },
  {
    id: '8',
    name: 'Blazers - Suits',
    description: 'Blazers - Suits',
    createdAt:  '12/05/19',
  },
  {
    id: '9',
    name: 'Jackets - Coats',
    description: 'Jackets - Coats',
    createdAt:  '12/05/19',
  },
  {
    id: '10',
    name: 'Underwear - Sleepwear',
    description: 'Underwear - Sleepwear',
    createdAt:  '12/05/19',
  },
  {
    id: '10',
    name: 'Beachwear',
    description: 'Beachwear',
    createdAt:  '12/05/19',
  },
];
